DELETE http://localhost:3003/api/blogs/64464e367fa9d6018483daf6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hdHRpIiwiaWQiOiI2NDQyNGY4YWQ2NDFiZDE3N2ZlZDU2YzYiLCJpYXQiOjE2ODIzMjkyNTl9.CKRCltMfzt2Tv-XvGAxjugm1qr0Y1EAgdDUegBMZs9M